CC      = gcc
CFLAGS  = -Wall -g -D_POSIX_SOURCE -D_BSD_SOURCE -std=c99 -Werror -pedantic

.SUFFIXES: .c .o

.PHONY: all clean

all: test 

test : test.o symtable.o linklist.o
clean:
	rm -f $(wildcard *.o)
	rm -f test
